// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cu36_tipocampo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cu36_tipocampo));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121135235_cu36_tipocampo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
