// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CAMBIOCAMPOSEL2_ALGORITMOS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CAMBIOCAMPOSEL2_ALGORITMOS));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291633175_CAMBIOCAMPOSEL2_ALGORITMOS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
