// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CU36_REVISION_14062018_AT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CU36_REVISION_14062018_AT));
        
        string IMigrationMetadata.Id
        {
            get { return "201806142150436_CU36_REVISION_14062018_AT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
