// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CambiosDesdeLaRamaUC24EvaluacionStandaresMinimos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambiosDesdeLaRamaUC24EvaluacionStandaresMinimos));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201315337_CambiosDesdeLaRamaUC24EvaluacionStandaresMinimos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
