// <auto-generated />
namespace SG_SST.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cu_36_newcampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cu_36_newcampos));
        
        string IMigrationMetadata.Id
        {
            get { return "201802120342020_cu_36_newcampos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
