using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SG_SST.Models.Incidentes
{
    [Table("Tbl_IncidentesEL6")]
    public class IncidentesEL6
    {
        [Key]
        public int PK_Incidentes_EL6 { get; set; }
        public int FK_Incidentes_EL6 { get; set; }
        public string PuestoEmpresaVI1 { get; set; }
        public string AgentesBiologicosVI1 { get; set; }
        public string FrasesVI1 { get; set; }
        public string RutinariaVI1 { get; set; }
        public string NORutinariaVI1 { get; set; }
        public string TiempoExposicionMesesVI1 { get; set; }
        public string TiempoExposicionHorasVI1 { get; set; }
        public string TLVCorregidoVI1 { get; set; }
        public string ConcentracionHalladaVI1 { get; set; }
        public string FechaMediacionDiaV1 { get; set; }
        public string FechaMediaMesV1 { get; set; }
        public string FechaMediaAnioV1 { get; set; }
        public string NivelRiesgoV1 { get; set; }
        public string ViaEntradaV1 { get; set; }
        public string PuestoEmpresaVI2 { get; set; }
        public string AgentesBiologicosVI2 { get; set; }
        public string FrasesVI2 { get; set; }
        public string RutinariaVI2 { get; set; }
        public string NORutinariaVI2 { get; set; }
        public string TiempoExposicionMesesVI2 { get; set; }
        public string TiempoExposicionHorasVI2 { get; set; }
        public string TLVCorregidoVI2 { get; set; }
        public string ConcentracionHalladaVI2 { get; set; }
        public string FechaMediacionDiaV2 { get; set; }
        public string FechaMediaMesV2 { get; set; }
        public string FechaMediaAnioV2 { get; set; }
        public string NivelRiesgoV2 { get; set; }
        public string ViaEntradaV2 { get; set; }
        public string PuestoEmpresaVI3 { get; set; }
        public string AgentesBiologicosVI3 { get; set; }
        public string FrasesVI3 { get; set; }
        public string RutinariaVI3 { get; set; }
        public string NORutinariaVI3 { get; set; }
        public string TiempoExposicionMesesVI3 { get; set; }
        public string TiempoExposicionHorasVI3 { get; set; }
        public string TLVCorregidoVI3 { get; set; }
        public string ConcentracionHalladaVI3 { get; set; }
        public string FechaMediacionDiaV3 { get; set; }
        public string FechaMediaMesV3 { get; set; }
        public string FechaMediaAnioV3 { get; set; }
        public string NivelRiesgoV3 { get; set; }
        public string ViaEntradaV3 { get; set; }
        public string PuestoEmpresaVI4 { get; set; }
        public string AgentesBiologicosVI4 { get; set; }
        public string FrasesVI4 { get; set; }
        public string RutinariaVI4 { get; set; }
        public string NORutinariaVI4 { get; set; }
        public string TiempoExposicionMesesVI4 { get; set; }
        public string TiempoExposicionHorasVI4 { get; set; }
        public string TLVCorregidoVI4 { get; set; }
        public string ConcentracionHalladaVI4 { get; set; }
        public string FechaMediacionDiaVI4 { get; set; }
        public string FechaMediaMesVI4 { get; set; }
        public string FechaMediaAnioVI4 { get; set; }
        public string NivelRiesgoVI4 { get; set; }
        public string ViaEntradaVI4 { get; set; }
        public string OficioEmpresa2V1 { get; set; }
        public string AgenteRelBiologico2VI { get; set; }
        public string FuenteAgente2VI1 { get; set; }
        public string MecanismoTransmicion2VI1 { get; set; }
        public string TipoActividadRutinaria2VI1 { get; set; }
        public string TipoActividadNoRutinaria2VI1 { get; set; }
        public string TiempoExposicionMeses2VI1 { get; set; }
        public string TiempoExposicionHoras2VI1 { get; set; }
        public string ConcentracionHallada2VI1 { get; set; }
        public string NivelRiesgo2VI1 { get; set; }
        public string Dia2VI1 { get; set; }
        public string Mes2VI1 { get; set; }
        public string Anio2VI1 { get; set; }
        public string FrecRiesgo2VI1 { get; set; }
        public string OficioEmpresa2V2 { get; set; }
        public string AgenteRelBiologico2VI2 { get; set; }
        public string FuenteAgente2VI2 { get; set; }
        public string MecanismoTransmicion2VI2 { get; set; }
        public string TipoActividadRutinaria2VI2 { get; set; }
        public string TipoActividadNoRutinaria2VI2 { get; set; }
        public string TiempoExposicionMeses2VI2 { get; set; }
        public string TiempoExposicionHoras2VI2 { get; set; }
        public string ConcentracionHallada2VI2 { get; set; }
        public string NivelRiesgo2VI2 { get; set; }
        public string Dia2VI2 { get; set; }
        public string Mes2VI2 { get; set; }
        public string Anio2VI2 { get; set; }
        public string FrecRiesgo2VI2 { get; set; }
        public string OficioEmpresa2V3 { get; set; }
        public string AgenteRelBiologico2VI3 { get; set; }
        public string FuenteAgente2VI3 { get; set; }
        public string MecanismoTransmicion2VI3 { get; set; }
        public string TipoActividadRutinaria2VI3 { get; set; }
        public string TipoActividadNoRutinaria2VI3 { get; set; }
        public string TiempoExposicionMeses2VI3 { get; set; }
        public string TiempoExposicionHoras2VI3 { get; set; }
        public string ConcentracionHallada2VI3 { get; set; }
        public string NivelRiesgo2VI3 { get; set; }
        public string Dia2VI3 { get; set; }
        public string Mes2VI3 { get; set; }
        public string Anio2VI3 { get; set; }
        public string FrecRiesgo2VI3 { get; set; }
        public string OficioEmpresa2V4 { get; set; }
        public string AgenteRelBiologico2VI4 { get; set; }
        public string FuenteAgente2VI4 { get; set; }
        public string MecanismoTransmicion2VI4 { get; set; }
        public string TipoActividadRutinaria2VI4 { get; set; }
        public string TipoActividadNoRutinaria2VI4 { get; set; }
        public string TiempoExposicionMeses2VI4 { get; set; }
        public string TiempoExposicionHoras2VI4 { get; set; }
        public string ConcentracionHallada2VI4 { get; set; }
        public string NivelRiesgo2VI4 { get; set; }
        public string Dia2VI4 { get; set; }
        public string Mes2VI4 { get; set; }
        public string Anio2VI4 { get; set; }
        public string FrecRiesgo2VI4 { get; set; }
        public string ExpoAccidentales2VI { get; set; }
        public string CargoOficioPuesto3VI { get; set; }
        public string Fuentes3VI { get; set; }
        public string Meses3VI { get; set; }
        public string HorasDia3VI { get; set; }
        public string NivelAmbiental3VI { get; set; }
        public string FMDia3VI { get; set; }
        public string FMMes3VI { get; set; }
        public string FMAnio3VI { get; set; }
        public string DosisRuido3VI { get; set; }
        public string FecMedDia3VI { get; set; }
        public string FecMedMes3VI { get; set; }
        public string FecMEdAnio3VI { get; set; }
        public string ExpSusQuimimcas3VI { get; set; }
        public string ExpoAccPrevias3VI { get; set; }
        public string CargoOficioPuesto3VI1 { get; set; }
        public string Fuentes3VI1 { get; set; }
        public string Meses3VI1 { get; set; }
        public string HorasDia3VI1 { get; set; }
        public string NivelAmbiental3VI1 { get; set; }
        public string FMDia3VI1 { get; set; }
        public string FMMes3VI1 { get; set; }
        public string FMAnio3VI1 { get; set; }
        public string DosisRuido3VI1 { get; set; }
        public string FecMedDia3VI1 { get; set; }
        public string FecMedMes3VI1 { get; set; }
        public string FecMEdAnio3VI1 { get; set; }
        public string ExpSusQuimimcas3VI1 { get; set; }
        public string ExpoAccPrevias3VI1 { get; set; }
        public string CargoOficioPuesto3VI2 { get; set; }
        public string Fuentes3VI2 { get; set; }
        public string Meses3VI2 { get; set; }
        public string HorasDia3VI2 { get; set; }
        public string NivelAmbiental3VI2 { get; set; }
        public string FMDia3VI2 { get; set; }
        public string FMMes3VI2 { get; set; }
        public string FMAnio3VI2 { get; set; }
        public string DosisRuido3VI2 { get; set; }
        public string FecMedDia3VI2 { get; set; }
        public string FecMedMes3VI2 { get; set; }
        public string FecMEdAnio3VI2 { get; set; }
        public string ExpSusQuimimcas3VI2 { get; set; }
        public string ExpoAccPrevias3VI2 { get; set; }
        public string CargoOficioPuesto3VI3 { get; set; }
        public string Fuentes3VI3 { get; set; }
        public string Meses3VI3 { get; set; }
        public string HorasDia3VI3 { get; set; }
        public string NivelAmbiental3VI3 { get; set; }
        public string FMDia3VI3 { get; set; }
        public string FMMes3VI3 { get; set; }
        public string FMAnio3VI3 { get; set; }
        public string DosisRuido3VI3 { get; set; }
        public string FecMedDia3VI3 { get; set; }
        public string FecMedMes3VI3 { get; set; }
        public string FecMEdAnio3VI3 { get; set; }
        public string ExpSusQuimimcas3VI3 { get; set; }
        public string ExpoAccPrevias3VI3 { get; set; }
        public string CargoOficio4VI1 { get; set; }
        public string DescActividad4VI1 { get; set; }
        public string Duracion4VI1 { get; set; }
        public string FrecActividad4VI1 { get; set; }
        public string TipoTrabajoActividad4VI1 { get; set; }
        public string WBTG4VI1 { get; set; }
        public string TipoExpMeses4VI1 { get; set; }
        public string TipoExpHD4VI1 { get; set; }
        public string TasaTrabajo4VI1 { get; set; }
        public string FechaMedDia4VI1 { get; set; }
        public string FechaMedMes4VI1 { get; set; }
        public string FechaMedAnio4VI1 { get; set; }
        public string CargoOficio4VI2 { get; set; }
        public string DescActividad4VI2 { get; set; }
        public string Duracion4VI2 { get; set; }
        public string FrecActividad4VI2 { get; set; }
        public string TipoTrabajoActividad4VI2 { get; set; }
        public string WBTG4VI2 { get; set; }
        public string TipoExpMeses4VI2 { get; set; }
        public string TipoExpHD4VI2 { get; set; }
        public string TasaTrabajo4VI2 { get; set; }
        public string FechaMedDia4VI2 { get; set; }
        public string FechaMedMes4VI2 { get; set; }
        public string FechaMedAnio4VI2 { get; set; }
        public string CargoOficio4VI3 { get; set; }
        public string DescActividad4VI3 { get; set; }
        public string Duracion4VI3 { get; set; }
        public string FrecActividad4VI3 { get; set; }
        public string TipoTrabajoActividad4VI3 { get; set; }
        public string WBTG4VI3 { get; set; }
        public string TipoExpMeses4VI3 { get; set; }
        public string TipoExpHD4VI3 { get; set; }
        public string TasaTrabajo4VI3 { get; set; }
        public string FechaMedDia4VI3 { get; set; }
        public string FechaMedMes4VI3 { get; set; }
        public string FechaMedAnio4VI3 { get; set; }
        public string CargoOficio4VI4 { get; set; }
        public string DescActividad4VI4 { get; set; }
        public string Duracion4VI4 { get; set; }
        public string FrecActividad4VI4 { get; set; }
        public string TipoTrabajoActividad4VI4 { get; set; }
        public string WBTG4VI4 { get; set; }
        public string TipoExpMeses4VI4 { get; set; }
        public string TipoExpHD4VI4 { get; set; }
        public string TasaTrabajo4VI4 { get; set; }
        public string FechaMedDia4VI4 { get; set; }
        public string FechaMedMes4VI4 { get; set; }
        public string FechaMedAnio4VI4 { get; set; }
        public string BooCauRelPrevVI13 { get; set; }
        public string CauRelPrevVI13 { get; set; }
        public string BooCauRelPrevVI14 { get; set; }
        public string CauRelPrevVI14 { get; set; }
        public string BooCauRelPrevVI15 { get; set; }
        public string CauRelPrevVI15 { get; set; }
        public string NivelRiesgoVI1 { get; set; }
        public string ViaEntradaVI1 { get; set; }
        public string NivelRiesgoV4 { get; set; }
        public string ViaEntradaV4 { get; set; }
        public string RadCargoEmpresa5VI1 { get; set; }
        public string RadDescripcionFuente5VI1 { get; set; }
        public string RadDescripcionAct5VI1 { get; set; }
        public string RadCondiciones5VI1 { get; set; }
        public string RadTEDia5VI1 { get; set; }
        public string RadTEMes5VI1 { get; set; }
        public string RadTEAnio5VI1 { get; set; }
        public string RadEvalAmbiental5VI1 { get; set; }
        public string RadFMDia5VI1 { get; set; }
        public string RadFMMes5VI1 { get; set; }
        public string RadFMAnio5VI1 { get; set; }
        public string RadCargoEmpresa5VI2 { get; set; }
        public string RadDescripcionFuente5VI2 { get; set; }
        public string RadDescripcionAct5VI2 { get; set; }
        public string RadCondiciones5VI2 { get; set; }
        public string RadTEDia5VI2 { get; set; }
        public string RadTEMes5VI2 { get; set; }
        public string RadTEAnio5VI2 { get; set; }
        public string RadEvalAmbiental5VI2 { get; set; }
        public string RadFMDia5VI2 { get; set; }
        public string RadFMMes5VI2 { get; set; }
        public string RadFMAnio5VI2 { get; set; }
        public string RadCargoEmpresa5VI3 { get; set; }
        public string RadDescripcionFuente5VI3 { get; set; }
        public string RadDescripcionAct5VI3 { get; set; }
        public string RadCondiciones5VI3 { get; set; }
        public string RadTEDia5VI3 { get; set; }
        public string RadTEMes5VI3 { get; set; }
        public string RadTEAnio5VI3 { get; set; }
        public string RadEvalAmbiental5VI3 { get; set; }
        public string RadFMDia5VI3 { get; set; }
        public string RadFMMes5VI3 { get; set; }
        public string RadFMAnio5VI3 { get; set; }
        public string RadCargoEmpresa5VI4 { get; set; }
        public string RadDescripcionFuente5VI4 { get; set; }
        public string RadDescripcionAct5VI4 { get; set; }
        public string RadCondiciones5VI4 { get; set; }
        public string RadTEDia5VI4 { get; set; }
        public string RadTEMes5VI4 { get; set; }
        public string RadTEAnio5V4 { get; set; }
        public string RadEvalAmbiental5VI4 { get; set; }
        public string RadFMDia5VI4 { get; set; }
        public string RadFMMes5VI4 { get; set; }
        public string RadFMAnio5VI4 { get; set; }
        public string VibCargoEmpresa6VI1 { get; set; }
        public string VibDescFuente6VI1 { get; set; }
        public string BooTipoVibCE6VI1 { get; set; }
        public string BooTipoVibMB6VI1 { get; set; }
        public string TiempoExpMeses6VI1 { get; set; }
        public string TiempoExpHD6VI1 { get; set; }
        public string VCE6VI1 { get; set; }
        public string VMB6VI1 { get; set; }
        public string AceTotal6VI1 { get; set; }
        public string EjeDominante6VI1 { get; set; }
        public string AceEjeDominante6VI1 { get; set; }
        public string Frecuencia6VI1 { get; set; }
        public string Aceleracion6VI1 { get; set; }
        public string FechaMedDia6VI1 { get; set; }
        public string FechaMedMes6VI1 { get; set; }
        public string FechaMedAnio6VI1 { get; set; }
        public string BooExpoRuido6VI1 { get; set; }
        public string VibCargoEmpresa6VI2 { get; set; }
        public string VibDescFuente6VI2 { get; set; }
        public string BooTipoVibCE6VI2 { get; set; }
        public string BooTipoVibMB6VI2 { get; set; }
        public string TiempoExpMeses6VI2 { get; set; }
        public string TiempoExpHD6VI2 { get; set; }
        public string VCE6VI2 { get; set; }
        public string VMB6VI2 { get; set; }
        public string AceTotal6VI2 { get; set; }
        public string EjeDominante6VI2 { get; set; }
        public string AceEjeDominante6VI2 { get; set; }
        public string Frecuencia6VI2 { get; set; }
        public string Aceleracion6VI2 { get; set; }
        public string FechaMedDia6VI2 { get; set; }
        public string FechaMedMes6VI2 { get; set; }
        public string FechaMedAnio6VI2 { get; set; }
        public string BooExpoRuido6VI2 { get; set; }
        public string VibCargoEmpresa6VI3 { get; set; }
        public string VibDescFuente6VI3 { get; set; }
        public string BooTipoVibCE6VI3 { get; set; }
        public string BooTipoVibMB6VI3 { get; set; }
        public string TiempoExpMeses6VI3 { get; set; }
        public string TiempoExpHD6VI3 { get; set; }
        public string VCE6VI3 { get; set; }
        public string VMB6VI3 { get; set; }
        public string AceTotal6VI3 { get; set; }
        public string EjeDominante6VI3 { get; set; }
        public string AceEjeDominante6VI3 { get; set; }
        public string Frecuencia6VI3 { get; set; }
        public string Aceleracion6VI3 { get; set; }
        public string FechaMedDia6VI3 { get; set; }
        public string FechaMedMes6VI3 { get; set; }
        public string FechaMedAnio6VI3 { get; set; }
        public string BooExpoRuido6VI3 { get; set; }
        public string VibCargoEmpresa6VI4 { get; set; }
        public string VibDescFuente6VI4 { get; set; }
        public string BooTipoVibCE6VI4 { get; set; }
        public string BooTipoVibMB6VI4 { get; set; }
        public string TiempoExpMeses6VI4 { get; set; }
        public string TiempoExpHD6VI4 { get; set; }
        public string VCE6VI4 { get; set; }
        public string VMB6VI4 { get; set; }
        public string AceTotal6VI4 { get; set; }
        public string EjeDominante6VI4 { get; set; }
        public string AceEjeDominante6VI4 { get; set; }
        public string Frecuencia6VI4 { get; set; }
        public string Aceleracion6VI4 { get; set; }
        public string FechaMedDia6VI4 { get; set; }
        public string FechaMedMes6VI4 { get; set; }
        public string FechaMedAnio6VI4 { get; set; }
        public string BooExpoRuido6VI4 { get; set; }
        public string VibCargoEmpresa6VI5 { get; set; }
        public string VibDescFuente6VI5 { get; set; }
        public string BooTipoVibCE6VI5 { get; set; }
        public string BooTipoVibMB6VI5 { get; set; }
        public string TiempoExpMeses6VI5 { get; set; }
        public string TiempoExpHD6VI5 { get; set; }
        public string VCE6VI5 { get; set; }
        public string VMB6VI5 { get; set; }
        public string AceTotal6VI5 { get; set; }
        public string EjeDominante6VI5 { get; set; }
        public string AceEjeDominante6VI5 { get; set; }
        public string Frecuencia6VI5 { get; set; }
        public string Aceleracion6VI5 { get; set; }
        public string FechaMedDia6VI5 { get; set; }
        public string FechaMedMes6VI5 { get; set; }
        public string FechaMedAnio6VI5 { get; set; }
        public string BooExpoRuido6VI5 { get; set; }
        public string VibCargoEmpresa6VI6 { get; set; }
        public string VibDescFuente6VI6 { get; set; }
        public string BooTipoVibCE6VI6 { get; set; }
        public string BooTipoVibMB6VI6 { get; set; }
        public string TiempoExpMeses6VI6 { get; set; }
        public string TiempoExpHD6VI6 { get; set; }
        public string VCE6VI6 { get; set; }
        public string VMB6VI6 { get; set; }
        public string AceTotal6VI6 { get; set; }
        public string EjeDominante6VI6 { get; set; }
        public string AceEjeDominante6VI6 { get; set; }
        public string Frecuencia6VI6 { get; set; }
        public string Aceleracion6VI6 { get; set; }
        public string FechaMedDia6VI6 { get; set; }
        public string FechaMedMes6VI6 { get; set; }
        public string FechaMedAnio6VI6 { get; set; }
        public string BooExpoRuido6VI6 { get; set; }
        public string DescEventoInv6VI { get; set; }
        public string FrecPresAltoVI1 { get; set; }
        public string FrecPresMedioVI1 { get; set; }
        public string FrecPresBajoVI1 { get; set; }
        public string TiempoExpAltoVI1 { get; set; }
        public string TiempoExpMedioVI1 { get; set; }
        public string TiempoExpBajoVI1 { get; set; }
        public string IntensidadAltoVI1 { get; set; }
        public string IntensidadMedioVI1 { get; set; }
        public string IntensidadBajoVI1 { get; set; }
        public string VarPsicoObservacionesVI1 { get; set; }
        public string FrecPresAltoVI2 { get; set; }
        public string FrecPresMedioVI2 { get; set; }
        public string FrecPresBajoVI2 { get; set; }
        public string TiempoExpAltoVI2 { get; set; }
        public string TiempoExpMedioVI2 { get; set; }
        public string TiempoExpBajoVI2 { get; set; }
        public string IntensidadAltoVI2 { get; set; }
        public string IntensidadMedioVI2 { get; set; }
        public string IntensidadBajoVI2 { get; set; }
        public string VarPsicoObservacionesVI2 { get; set; }
        public string FrecPresAltoVI3 { get; set; }
        public string FrecPresMedioVI3 { get; set; }
        public string FrecPresBajoVI3 { get; set; }
        public string TiempoExpAltoVI3 { get; set; }
        public string TiempoExpMedioVI3 { get; set; }
        public string TiempoExpBajoVI3 { get; set; }
        public string IntensidadAltoVI3 { get; set; }
        public string IntensidadMedioVI3 { get; set; }
        public string IntensidadBajoVI3 { get; set; }
        public string VarPsicoObservacionesVI3 { get; set; }
        public string FrecPresAltoVI4 { get; set; }
        public string FrecPresMedioVI4 { get; set; }
        public string FrecPresBajoVI4 { get; set; }
        public string TiempoExpAltoVI4 { get; set; }
        public string TiempoExpMedioVI4 { get; set; }
        public string TiempoExpBajoV4 { get; set; }
        public string IntensidadAltoVI4 { get; set; }
        public string IntensidadMedioVI4 { get; set; }
        public string IntensidadBajoVI4 { get; set; }
        public string VarPsicoObservacionesVI4 { get; set; }
        public string IntensidadAltaVI1 { get; set; }
        public string IntensidadMediaVI1 { get; set; }
        public string IntensidadBajaVI1 { get; set; }
        public string IntensidadObservVI1 { get; set; }
        public string IntensidadAltaVI2 { get; set; }
        public string IntensidadMediaVI2 { get; set; }
        public string IntensidadBajaVI2 { get; set; }
        public string IntensidadObservVI2 { get; set; }
        public string NivelRiesgoLabVI { get; set; }
        public string NivelRiesgoExtralabVI { get; set; }
        public string NivelRiesgoIndiviVI { get; set; }
        public string NivelEstresVI { get; set; }
        public string BooEsfuerzoBrazosManos1 { get; set; }
        public string BooPostPieProlongada { get; set; }
        public string BooPostPieSedente { get; set; }
        public string BooPosturaIncomodaBrazosManos { get; set; }
        public string BooEsfuerzoBrazosManos { get; set; }
        public string BooPosturaIncomodaEspalda { get; set; }
        public string BooLabRepetitivaColumna { get; set; }
        public string BooLabRepetitivaBrazoMuMano { get; set; }
        public string BooPeriodoRecuperacionFisica { get; set; }
        public string BooEsfuerzoManos { get; set; }
        public string BooEsfuerzoCuerpo { get; set; }
        public string BooManipulacionCargas { get; set; }
        public string DMEResumen { get; set; }
        public string BooCauRelPrevVI1 { get; set; }
        public string CauRelPrevVI1 { get; set; }
        public string BooCauRelPrevVI2 { get; set; }
        public string CauRelPrevVI2 { get; set; }
        public string BooCauRelPrevVI3 { get; set; }
        public string CauRelPrevVI3 { get; set; }
        public string BooCauRelPrevVI4 { get; set; }
        public string CauRelPrevVI4 { get; set; }
        public string BooCauRelPrevVI5 { get; set; }
        public string CauRelPrevVI5 { get; set; }
        public string BooCauRelPrevVI6 { get; set; }
        public string CauRelPrevVI6 { get; set; }
        public string BooCauRelPrevVI7 { get; set; }
        public string CauRelPrevVI7 { get; set; }
        public string BooCauRelPrevVI8 { get; set; }
        public string CauRelPrevVI8 { get; set; }
        public string BooCauRelPrevVI9 { get; set; }
        public string CauRelPrevVI9 { get; set; }
        public string BooCauRelPrevVI10 { get; set; }
        public string CauRelPrevVI10 { get; set; }
        public string BooCauRelPrevVI11 { get; set; }
        public string CauRelPrevVI11 { get; set; }
        public string BooCauRelPrevVI12 { get; set; }
        public string CauRelPrevVI12 { get; set; }
        public string OtrosDatosInteresVI { get; set; }
        public string CausasEnfermedadLaboralVI { get; set; }
        public string NitEmpresa { get; set; }
    }
}
